import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias libs.plugins.java.gradle.plugin
    alias libs.plugins.org.jetbrains.kotlin.jvm
    alias libs.plugins.org.jetbrains.kotlinx.binary.compatibility.validator
    alias libs.plugins.org.jetbrains.kotlinx.kover
}

apply from: layout.settingsDirectory.dir("gradle").file("publish.gradle")

kotlin {
    explicitApi()
    compilerOptions.jvmTarget = libs.versions.jdk.map { JvmTarget.fromTarget(it) }
}

tasks.withType(JavaCompile).configureEach {
    options.release.set(libs.versions.jdk.map { it.toInteger() })
}

test {
    useJUnitPlatform()
    testLogging {
        events TestLogEvent.FAILED, TestLogEvent.SKIPPED, TestLogEvent.STANDARD_OUT, TestLogEvent.STANDARD_ERROR
        exceptionFormat TestExceptionFormat.FULL
    }
}

gradlePlugin {
    plugins {
        register("log2timber") {
            id = "log2timber"
            implementationClass = "io.github.ryunen344.log2timber.Log2TimberPlugin"
        }
    }
}

dependencies {
    implementation libs.org.ow2.asm.util
    compileOnly libs.com.android.tools.build.gradle.api
    compileOnly gradleApi()
    compileOnly fileTree(dir: "${gradle.gradleHomeDir}/lib", include: "gradle-kotlin-dsl-*.jar")
    testImplementation libs.org.ow2.asm.test
    testImplementation libs.com.android.tools.build.gradle
    testImplementation gradleTestKit()
    testImplementation libs.com.willowtreeapps.assertk
    testImplementation libs.org.junit.jupiter.jupiter
    testRuntimeOnly libs.org.junit.platform.launcher
}
