# $schema: https://json.schemastore.org/github-workflow.json
name: check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: check-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - uses: reviewdog/action-setup@v1
      - name: run android lint
        shell: bash
        run: |
          ./gradlew :app-groovy:lintDebug :app-kts:lintDemoDebug :app-test:lintDebug
      - name: run detekt
        shell: bash
        run: |
          ./gradlew detekt
      - name: run reviewdog review
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat app-groovy/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="app-groovy android lint" -reporter=github-pr-review;
          cat app-kts/build/reports/lint-results-demoDebug.sarif | reviewdog -f=sarif -name="app-kts android lint" -reporter=github-pr-review;
          cat app-test/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="app-test android lint" -reporter=github-pr-review;
          cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter=github-pr-review;
      - name: run reviewdog suggest
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew :app-groovy:lintFix :app-kts:lintFix :app-test:lintFix detekt -PautoCorrect --quiet --continue || true;
          TMPFILE=$(mktemp);
          git diff >"${TMPFILE}";
          git stash -u || git stash drop;
          cat "${TMPFILE}" | reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review;

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: check api file
        shell: bash
        run: |
          ./gradlew apiCheck

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: publish
        shell: bash
        run: |
          ./gradlew publishAllPublicationsToLocalRepository

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: plugin test
        shell: bash
        run: |
          ./gradlew koverXmlReport
      - name: functional test
        shell: bash
        run: |
          ./gradlew :app-test:koverXmlReportDebug
      - uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: unit-test-result
          path: '**/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false
      - uses: madrapps/jacoco-report@v1.7.2
        if: ${{ !cancelled() }}
        with:
          paths: |
            ${{ github.workspace }}/plugin/build/reports/kover/report.xml
            ${{ github.workspace }}/app-test/build/reports/kover/reportDebug.xml
          title: coverage report
          update-comment: true
          comment-type: both
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
